// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoonMissing.Data.Deploy;

#nullable disable

namespace MoonMissing.Data.Deploy.Migrations
{
    [DbContext(typeof(MoonMissingDeployDbContext))]
    [Migration("20220130012411_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("MoonMissing.Data.Entities.Kingdom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Kingdom");
                });

            modelBuilder.Entity("MoonMissing.Data.Entities.Moon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMultiMoon")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRockMoon")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSubAreaMoon")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("KingdomId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MoonName")
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Quadrant")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KingdomId");

                    b.ToTable("Moon");
                });

            modelBuilder.Entity("MoonMissing.Data.Entities.Moon", b =>
                {
                    b.HasOne("MoonMissing.Data.Entities.Kingdom", "Kingdom")
                        .WithMany("Moons")
                        .HasForeignKey("KingdomId");

                    b.Navigation("Kingdom");
                });

            modelBuilder.Entity("MoonMissing.Data.Entities.Kingdom", b =>
                {
                    b.Navigation("Moons");
                });
#pragma warning restore 612, 618
        }
    }
}
