// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoonMissing.Data.Deploy;

#nullable disable

namespace MoonMissing.Data.Deploy.Migrations
{
    [DbContext(typeof(MoonMissingDeployDbContext))]
    [Migration("20220123100220_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MoonMissing.Data.Entities.Kingdom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Kingdom");
                });

            modelBuilder.Entity("MoonMissing.Data.Entities.Moon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("KingdomId")
                        .HasColumnType("int");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KingdomId");

                    b.ToTable("Moon");
                });

            modelBuilder.Entity("MoonMissing.Data.Entities.Moon", b =>
                {
                    b.HasOne("MoonMissing.Data.Entities.Kingdom", null)
                        .WithMany("Moons")
                        .HasForeignKey("KingdomId");
                });

            modelBuilder.Entity("MoonMissing.Data.Entities.Kingdom", b =>
                {
                    b.Navigation("Moons");
                });
#pragma warning restore 612, 618
        }
    }
}
